export const USER_ACTION_TYPES = {
    CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
    CHECK_USER_SESSION_SUCCESS:'user/CHECK_USER_SESSION_SUCCESS',
    SIGN_IN_START: 'user/SIGN_IN_START',
    SIGN_IN_SUCCESS: 'user/SIGN_IN_SUCCESS',
    SIGN_IN_FAILED: 'user/SIGN_IN_FAILED',
    SIGN_UP_START: 'user/SIGN_UP_START',
    SIGN_OUT_START: 'user/SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'user/SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILED: 'user/SIGN_OUT_FAILED',
    
}