export const CAMPS_ACTION_TYPES = {
    'FETCH_CAMPS_START': 'camps/FETCH_CAMPS_START',
    'FETCH_CAMPS_SUCCESS': 'camps/FETCH_CAMPS_SUCCESS',
    'FETCH_CAMPS_FAILED': 'camps/FETCH_CAMPS_FAILED',
    'UPLOAD_CAMP_START': 'camps/UPLOAD_CAMP_START',
    'UPLOAD_CAMP_SUCCESS': 'camps/UPLOAD_CAMP_SUCCESS',
    'UPLOAD_CAMP_FAILED': 'camps/UPLOAD_CAMP_FAILED',
    'UPLOAD_REVIEW_START': 'camps/UPLOAD_REVIEW_START',
    'UPLOAD_REVIEW_SUCCESS': 'camps/UPLOAD_REVIEW_SUCCESS',
    'UPLOAD_REVIEW_FAILED': 'camps/UPLOAD_REVIEW_FAILED',
    'DELETE_REVIEW_START': 'camps/DELETE_REVIEW_START',
    'DELETE_REVIEW_SUCCESS': 'camps/DELETE_REVIEW_SUCCESS',
    'DELETE_REVIEW_FAILED': 'camps/DELETE_REVIEW_FAILED',
}